Repository ros-controls/ros2_control, pull requests merged in 2023-11, with the labels that each got.

#1107 Sort controllers while configuring instead of while activating
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_chainable_controller/test_chainable_controller.cpp
  controller_manager/test/test_controller/test_controller.cpp
  controller_manager/test/test_controller_manager.cpp
  controller_manager/test/test_controller_manager_srvs.cpp
  controller_manager/test/test_load_controller.cpp
Labels: backport-humble

#1151 [MockHardware] Fix the issues where hardware with multiple interfaces can not be started because of a logical bug added when adding dynamics calculation functionality.
  hardware_interface/src/mock_components/generic_system.cpp
  hardware_interface/test/mock_components/test_generic_system.cpp
Labels: bug, rolling

#1155 Add iron branch
  .github/mergify.yml
  .github/workflows/iron-abi-compatibility.yml
  .github/workflows/iron-binary-build-main.yml
  .github/workflows/iron-binary-build-testing.yml
  .github/workflows/iron-semi-binary-build-main.yml
  .github/workflows/iron-semi-binary-build-testing.yml
  .github/workflows/iron-source-build.yml
  README.md
Labels: rolling, holding

#1088 Pass URDF to controllers on init
  controller_interface/include/controller_interface/controller_interface_base.hpp
  controller_interface/src/controller_interface_base.cpp
  controller_interface/test/test_chainable_controller_interface.cpp
  controller_interface/test/test_controller_interface.cpp
  controller_interface/test/test_controller_with_options.cpp
  controller_interface/test/test_controller_with_options.hpp
  controller_manager/include/controller_manager/controller_manager.hpp
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_controller/test_controller.hpp
  controller_manager/test/test_controller_failed_init/test_controller_failed_init.cpp
  controller_manager/test/test_controller_failed_init/test_controller_failed_init.hpp
  controller_manager/test/test_controller_manager.cpp
  controller_manager/test/test_controller_manager_srvs.cpp
Labels: rolling, holding

#1157 [Humble] Controller sorting
  controller_manager/include/controller_manager/controller_manager.hpp
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_chainable_controller/test_chainable_controller.cpp
  controller_manager/test/test_controller/test_controller.cpp
  controller_manager/test/test_controller_manager.cpp
  controller_manager/test/test_controller_manager_srvs.cpp
  controller_manager/test/test_controllers_chaining_with_controller_manager.cpp
  controller_manager/test/test_load_controller.cpp
Labels: humble

#1150 [MockHardware] Remove all deprecated options and deprecated plugins from the library.
  hardware_interface/CMakeLists.txt
  hardware_interface/fake_components_plugin_description.xml
  hardware_interface/include/fake_components/generic_system.hpp
  hardware_interface/include/fake_components/visibility_control.h
  hardware_interface/src/mock_components/fake_generic_system.cpp
  hardware_interface/src/mock_components/generic_system.cpp
  hardware_interface/test/mock_components/test_generic_system.cpp
Labels: enhancement, rolling, holding

#1165 Fix the controller sorting bug when the interfaces are not configured (fixes #1164)
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_chainable_controller/test_chainable_controller.cpp
  controller_manager/test/test_controller/test_controller.cpp
Labels: backport-humble, backport-iron

#1141 Pass controller manager update rate on the init of the controller interface
  controller_interface/include/controller_interface/controller_interface_base.hpp
  controller_interface/src/controller_interface_base.cpp
  controller_interface/test/test_chainable_controller_interface.cpp
  controller_interface/test/test_controller_interface.cpp
  controller_interface/test/test_controller_with_options.cpp
  controller_interface/test/test_controller_with_options.hpp
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_controller_failed_init/test_controller_failed_init.cpp
  controller_manager/test/test_controller_failed_init/test_controller_failed_init.hpp
Labels: rolling, holding

#1173 [ControllerInterface] Avoid warning about conversion from `int64_t` to `unsigned int`
  controller_interface/src/controller_interface_base.cpp
Labels: enhancement
