Repository ros-controls/ros2_control, pull requests merged in 2023-06, with the labels that each got.

#1027 [MockHardware] Enable disabling of command to simulate HW failures.
  hardware_interface/doc/mock_components_userdoc.rst
  hardware_interface/include/mock_components/generic_system.hpp
  hardware_interface/src/mock_components/generic_system.cpp
  hardware_interface/test/mock_components/test_generic_system.cpp
Labels: enhancement

#940 [CM] Use `robot_description` topic instead of parameter and don't crash on empty URDF 🦿
  controller_manager/CMakeLists.txt
  controller_manager/include/controller_manager/controller_manager.hpp
  controller_manager/package.xml
  controller_manager/src/controller_manager.cpp
  controller_manager/test/controller_manager_test_common.hpp
  controller_manager/test/test_controller_manager_urdf_passing.cpp
  hardware_interface/doc/mock_components_userdoc.rst
  hardware_interface/include/hardware_interface/resource_manager.hpp
  hardware_interface/src/resource_manager.cpp
  hardware_interface/test/test_resource_manager.cpp
Labels: iron

#1059 [CM] Optimize output when using robot description topic and give output about correct topic even remapped.
  controller_manager/src/controller_manager.cpp
Labels: enhancement

#1060 Optimize list hardware components output and code for better readability.
  ros2controlcli/ros2controlcli/verb/list_hardware_components.py
Labels: enhancement

#1046 Enable setting of initial state in HW compoments
  controller_manager/doc/userdoc.rst
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_hardware_management_srvs.cpp
  hardware_interface/include/hardware_interface/resource_manager.hpp
  hardware_interface/src/resource_manager.cpp
Labels: enhancement, backport-humble
