Repository ros-controls/ros2_control, pull requests merged in 2024-02, with the labels that each got.

#1356 [CM] Use explicit constants in controller tests.
  controller_manager/test/test_load_controller.cpp
Labels: enhancement, backport-humble, backport-iron

#1338 [RHEL-CI] Source underlay with generate_parameter_library
  .github/workflows/humble-rhel-binary-build.yml
  .github/workflows/iron-rhel-binary-build.yml
  .github/workflows/rolling-rhel-binary-build.yml
Labels: backport-humble, backport-iron

#1363 check for state of the controller node before cleanup
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_controller_manager_srvs.cpp
Labels: bug, backport-humble, backport-iron

#1342 Move hardware interface README content to sphinx documentation
  hardware_interface/README.md
  hardware_interface/doc/different_update_rates_userdoc.rst
  hardware_interface/doc/hardware_components_userdoc.rst
Labels: backport-humble, backport-iron

#1395 Move reviewer-lottery list to ros2_control_ci
  .github/reviewer-lottery.yml
  .github/workflows/reviewer_lottery.yml
Labels: backport-humble, backport-iron

#1402 [CI] Use reusable-reviewer-lottery from ros2_control_ci
  .github/workflows/reviewer_lottery.yml
Labels: backport-humble, backport-iron

#1413 [CI] Code coverage + pre-commit
  .github/workflows/ci-coverage-build.yml
  .github/workflows/ci-format.yml
  .github/workflows/ci-ros-lint.yml
  .github/workflows/humble-coverage-build.yml
  .github/workflows/humble-pre-commit.yml
  .github/workflows/iron-coverage-build.yml
  .github/workflows/iron-pre-commit.yml
  .github/workflows/rolling-coverage-build.yml
  .github/workflows/rolling-pre-commit.yml
  .github/workflows/update-pre-commit.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  controller_manager/src/controller_manager.cpp
  controller_manager/test/controller_manager_test_common.hpp
  hardware_interface/test/test_handle.cpp
  rqt_controller_manager/setup.py
Labels: backport-humble, backport-iron

#1409 Added spawner colours to `list_controllers` depending upon active or inactive
  ros2controlcli/ros2controlcli/verb/list_controllers.py
Labels: backport-humble, backport-iron
