Repository ros-controls/ros2_control, pull requests merged in 2024-06, with the labels that each got.

#1497 Add doc page about joint kinematics
  doc/index.rst
  hardware_interface/doc/joints_userdoc.rst
Labels: backport-humble, backport-iron

#1563 [docs] Fix link to gazebosim.org
  hardware_interface/doc/joints_userdoc.rst
Labels: backport-humble, backport-iron

#1580 Small improvements to the error output in component parser to make debugging easier.
  hardware_interface/src/component_parser.cpp
Labels: enhancement, backport-humble, backport-iron

#1354 [RM] Rename `load_urdf` method to `load_and_initialize_components` and add error handling there to avoid stack crashing when error happens.
  controller_manager/include/controller_manager/controller_manager.hpp
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_controller_manager_urdf_passing.cpp
  hardware_interface/include/hardware_interface/resource_manager.hpp
  hardware_interface/src/resource_manager.cpp
  hardware_interface/test/mock_components/test_generic_system.cpp
  hardware_interface_testing/test/test_components/test_actuator.cpp
  hardware_interface_testing/test/test_components/test_sensor.cpp
  hardware_interface_testing/test/test_components/test_system.cpp
  hardware_interface_testing/test/test_resource_manager.cpp
  hardware_interface_testing/test/test_resource_manager.hpp
  ros2_control_test_assets/include/ros2_control_test_assets/descriptions.hpp
Labels: bug, enhancement, high-priority

#1455 [rqt_controller_manager] Add hardware components
  controller_manager/doc/images/rqt_controller_manager.png
  controller_manager/doc/userdoc.rst
  rqt_controller_manager/package.xml
  rqt_controller_manager/resource/controller_manager.ui
  rqt_controller_manager/resource/popup_info.ui
  rqt_controller_manager/rqt_controller_manager/controller_manager.py
Labels: enhancement, backport-humble, backport-iron

#1484 Add custom rosdoc2 config for ros2_control metapackage
  .github/workflows/rosdoc2.yml
  .pre-commit-config.yaml
  doc/Doxyfile
  ros2_control/doc/conf.py
  ros2_control/doc/index.rst
  ros2_control/package.xml
  ros2_control/rosdoc2.yaml
Labels: backport-humble, backport-iron
