Repository ros-controls/ros2_control, pull requests merged in 2024-01, with the labels that each got.

#1263 [docs] Remove joint_state_controller
  controller_manager/controller_manager/launch_utils.py
  ros2controlcli/doc/userdoc.rst
Labels: backport-humble, backport-iron

#1243 [ResourceManager] adds test for uninitialized hardware
  hardware_interface/test/test_components/test_actuator.cpp
  hardware_interface/test/test_components/test_components.xml
  hardware_interface/test/test_components/test_sensor.cpp
  hardware_interface/test/test_components/test_system.cpp
  hardware_interface/test/test_resource_manager.cpp
  ros2_control_test_assets/include/ros2_control_test_assets/descriptions.hpp
Labels: backport-iron

#1273 Fix rqt controller manager
  controller_manager/controller_manager/controller_manager_services.py
  rqt_controller_manager/rqt_controller_manager/controller_manager.py
Labels: backport-humble, backport-iron

#1271 Initialize the controller manager services after initializing resource manager
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_hardware_management_srvs.cpp
Labels: backport-iron

#1279 Fix multiple calls of cleanup when system is unconfigured
  hardware_interface/src/actuator.cpp
  hardware_interface/src/sensor.cpp
  hardware_interface/src/system.cpp
  hardware_interface/test/test_component_interfaces.cpp
Labels: backport-humble, backport-iron

#1218 Add additional checks for non existing and not available interfaces.
  hardware_interface/CMakeLists.txt
  hardware_interface/include/hardware_interface/resource_manager.hpp
  hardware_interface/src/resource_manager.cpp
  hardware_interface/test/mock_components/test_generic_system.cpp
  hardware_interface/test/test_components/test_actuator.cpp
  hardware_interface/test/test_hardware_components/test_system_with_command_modes.cpp
  hardware_interface/test/test_resource_manager.cpp
  hardware_interface/test/test_resource_manager.hpp
  hardware_interface/test/test_resource_manager_prepare_perform_switch.cpp
Labels: bug, enhancement, high-priority, backport-humble, backport-iron

#1301 Fix crash for missing urdf in resource manager
  hardware_interface/include/hardware_interface/resource_manager.hpp
  hardware_interface/src/resource_manager.cpp
Labels: backport-humble, backport-iron

#1227 [CM] Better readability and maintainability: rename variables, move code to more logical places 🔧
  controller_manager/src/controller_manager.cpp
Labels: enhancement

#1326 [RHEL-CI] Rename workflow and don't run on push
  .github/workflows/humble-rhel-binary-build.yml
  .github/workflows/iron-rhel-binary-build.yml
  .github/workflows/rolling-rhel-binary-build.yml
Labels: backport-humble, backport-iron

#1310 [CI] Add debian source build job
  .github/workflows/humble-debian-build.yml
  .github/workflows/iron-debian-build.yml
  .github/workflows/rolling-debian-build.yml
Labels: backport-humble, backport-iron

#1325 Move `test_components` to own package
  .github/workflows/ci-coverage-build.yml
  .github/workflows/ci-ros-lint.yml
  controller_manager/package.xml
  hardware_interface/CMakeLists.txt
  hardware_interface_testing/CMakeLists.txt
  hardware_interface_testing/README.md
  hardware_interface_testing/package.xml
  hardware_interface_testing/test/test_components/test_actuator.cpp
  hardware_interface_testing/test/test_components/test_components.xml
  hardware_interface_testing/test/test_components/test_sensor.cpp
  hardware_interface_testing/test/test_components/test_system.cpp
  hardware_interface_testing/test/test_resource_manager.cpp
  hardware_interface_testing/test/test_resource_manager.hpp
  hardware_interface_testing/test/test_resource_manager_prepare_perform_switch.cpp
Labels: backport-humble, backport-iron
