Repository ros-controls/ros2_control, pull requests merged in 2025-09, with the labels that each got.

#2509 Fix the CPU affinity of the ros2_control_node
  controller_manager/src/ros2_control_node.cpp
Labels: backport-jazzy

#2507 Add pre-release
  .github/workflows/humble-pre-release.yml
  .github/workflows/humble-semi-binary-downstream-3rd-party-build.yml
  .github/workflows/jazzy-pre-release.yml
  .github/workflows/jazzy-semi-binary-downstream-3rd-party-build.yml
  .github/workflows/rolling-pre-release.yml
  .github/workflows/rolling-semi-binary-downstream-3rd-party-build.yml
  downstream.humble.repos
  downstream.jazzy.repos
  downstream.kilted.repos
  downstream.rolling.repos
Labels: backport-humble, backport-jazzy, check-prerelease

#2449 Publish controller manager statistics to better introspect the timings
  controller_manager/include/controller_manager/controller_manager.hpp
  controller_manager/include/controller_manager/controller_spec.hpp
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_controller_manager.cpp
  doc/introspection.rst
  doc/release_notes.rst
  hardware_interface/include/hardware_interface/introspection.hpp
  hardware_interface/include/hardware_interface/types/statistics_types.hpp
  hardware_interface/src/hardware_component.cpp
Labels: backport-jazzy

#2530 CI: Deactivate BUILD_TESTING for target ws and skip some upstream packages
  .github/workflows/rolling-semi-binary-build-win.yml
Labels: backport-humble, backport-jazzy

#2486 Enable controller activation for inactive hardware component
  hardware_interface/src/resource_manager.cpp
  hardware_interface_testing/test/test_resource_manager_prepare_perform_switch.cpp
Labels: backport-jazzy

#2560 Use auto dependency management for windows workflow
  .github/workflows/rolling-semi-binary-build-win.yml
  ros2_control.humble.repos
  ros2_control.jazzy.repos
  ros2_control.kilted.repos
  ros2_control.rolling.repos
  ros2_control.windows.rolling.repos
  ros_controls.humble.repos
  ros_controls.jazzy.repos
  ros_controls.kilted.repos
  ros_controls.rolling.repos
Labels: backport-humble, backport-jazzy

#2557 Fix the skipped cycles of controllers running at different rate
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_controller_manager.cpp
Labels: backport-jazzy

#1522 Fix exclusive hardware control mode switching on controller failed activation
  controller_manager/CMakeLists.txt
  controller_manager/doc/userdoc.rst
  controller_manager/src/controller_manager.cpp
  controller_manager/test/test_controller_failed_activate/test_controller_failed_activate.cpp
  controller_manager/test/test_controller_failed_activate/test_controller_failed_activate.hpp
  controller_manager/test/test_controller_failed_activate/test_controller_failed_activate.xml
  controller_manager/test/test_release_interfaces.cpp
  hardware_interface_testing/test/test_components/test_components.xml
Labels: bug, backport-humble, backport-jazzy
