Repository ros-controls/ros2_control, pull requests merged in 2025-05, with the labels that each got.

#2244 Use `warning` attribute of RcutilsLogger
  controller_manager/controller_manager/controller_manager_services.py
  controller_manager/controller_manager/hardware_spawner.py
  controller_manager/controller_manager/spawner.py
Labels: backport-jazzy

#2223 Supress the deprecation warnings of the hardware_interface API
  controller_manager/src/controller_manager.cpp
  hardware_interface/include/hardware_interface/handle.hpp
  hardware_interface/include/hardware_interface/loaned_command_interface.hpp
  hardware_interface/include/hardware_interface/loaned_state_interface.hpp
  hardware_interface/include/hardware_interface/resource_manager.hpp
  hardware_interface/include/mock_components/generic_system.hpp
  hardware_interface/src/actuator.cpp
  hardware_interface/src/resource_manager.cpp
  hardware_interface/src/sensor.cpp
  hardware_interface/src/system.cpp
  hardware_interface/test/mock_components/test_generic_system.cpp
  hardware_interface/test/test_component_interfaces.cpp
  hardware_interface/test/test_handle.cpp
  hardware_interface/test/test_hardware_components/test_force_torque_sensor.cpp
  hardware_interface/test/test_hardware_components/test_imu_sensor.cpp
  hardware_interface/test/test_hardware_components/test_single_joint_actuator.cpp
  hardware_interface/test/test_hardware_components/test_system_with_command_modes.cpp
  hardware_interface/test/test_hardware_components/test_two_joint_system.cpp
  hardware_interface_testing/test/test_resource_manager.cpp
  transmission_interface/include/transmission_interface/handle.hpp
Labels: backport-jazzy

#2253 Add new `Handle` constructor for easier initialization
  hardware_interface/include/hardware_interface/handle.hpp
  hardware_interface/include/hardware_interface/hardware_info.hpp
  hardware_interface/test/test_handle.cpp
Labels: backport-jazzy

#2266 Use target_link_libraries instead of ament_target_dependencies
  controller_interface/CMakeLists.txt
  controller_manager/CMakeLists.txt
  hardware_interface/CMakeLists.txt
  hardware_interface_testing/CMakeLists.txt
  joint_limits/CMakeLists.txt
  joint_limits/include/joint_limits/joint_saturation_limiter.hpp
  joint_limits/include/joint_limits/joint_soft_limiter.hpp
  transmission_interface/CMakeLists.txt
Labels: backport-jazzy

#1837 Fix fourbarlinkage
  transmission_interface/include/transmission_interface/four_bar_linkage_transmission.hpp
  transmission_interface/test/four_bar_linkage_transmission_test.cpp
Labels: backport-humble, stale, backport-jazzy

#2296 Add missing github_url links
  doc/debugging.rst
  doc/introspection.rst
Labels: backport-humble, backport-jazzy
